// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_QuanLy_PolyCafe.Data;

#nullable disable

namespace Web_QuanLy_PolyCafe.Migrations
{
    [DbContext(typeof(PolyCafeDbContext))]
    [Migration("20260406005525_InitPolyCafe")]
    partial class InitPolyCafe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "CAT01",
                            Description = "Các loại cà phê truyền thống và hiện đại",
                            IsDeleted = false,
                            Name = "Cà Phê"
                        },
                        new
                        {
                            Id = "CAT02",
                            Description = "Trà sữa Đài Loan, trân châu các loại",
                            IsDeleted = false,
                            Name = "Trà Sữa"
                        },
                        new
                        {
                            Id = "CAT03",
                            Description = "Sinh tố hoa quả tươi nguyên chất",
                            IsDeleted = false,
                            Name = "Sinh Tố"
                        },
                        new
                        {
                            Id = "CAT04",
                            Description = "Nước ép trái cây tươi 100%",
                            IsDeleted = false,
                            Name = "Nước Ép"
                        },
                        new
                        {
                            Id = "CAT05",
                            Description = "Trà kết hợp hoa quả tươi",
                            IsDeleted = false,
                            Name = "Trà Trái Cây"
                        },
                        new
                        {
                            Id = "CAT06",
                            Description = "Thức uống từ bột trà xanh Nhật Bản",
                            IsDeleted = false,
                            Name = "Matcha"
                        },
                        new
                        {
                            Id = "CAT07",
                            Description = "Thức uống từ cacao và chocolate",
                            IsDeleted = false,
                            Name = "Chocolate"
                        },
                        new
                        {
                            Id = "CAT08",
                            Description = "Thức uống xay đá mát lạnh",
                            IsDeleted = false,
                            Name = "Đá Xay"
                        },
                        new
                        {
                            Id = "CAT09",
                            Description = "Soda kết hợp xi rô nhiều vị",
                            IsDeleted = false,
                            Name = "Soda"
                        },
                        new
                        {
                            Id = "CAT10",
                            Description = "Cà phê sữa Ý kiểu latte",
                            IsDeleted = false,
                            Name = "Latte"
                        },
                        new
                        {
                            Id = "CAT11",
                            Description = "Cà phê cappuccino bọt sữa mịn",
                            IsDeleted = false,
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = "CAT12",
                            Description = "Cà phê espresso đậm đặc",
                            IsDeleted = false,
                            Name = "Espresso"
                        },
                        new
                        {
                            Id = "CAT13",
                            Description = "Cà phê ủ lạnh 12-24 giờ",
                            IsDeleted = false,
                            Name = "Cold Brew"
                        },
                        new
                        {
                            Id = "CAT14",
                            Description = "Thức uống từ sữa chua",
                            IsDeleted = false,
                            Name = "Yogurt"
                        },
                        new
                        {
                            Id = "CAT15",
                            Description = "Hoa quả dầm sữa chua, đá bào",
                            IsDeleted = false,
                            Name = "Hoa Quả Dầm"
                        },
                        new
                        {
                            Id = "CAT16",
                            Description = "Trà từ hoa khô tự nhiên",
                            IsDeleted = false,
                            Name = "Trà Hoa"
                        },
                        new
                        {
                            Id = "CAT17",
                            Description = "Thức uống kết hợp kem tươi",
                            IsDeleted = false,
                            Name = "Kem"
                        },
                        new
                        {
                            Id = "CAT18",
                            Description = "Nước dừa tươi và biến tấu",
                            IsDeleted = false,
                            Name = "Nước Dừa"
                        },
                        new
                        {
                            Id = "CAT19",
                            Description = "Chanh muối, chanh leo các loại",
                            IsDeleted = false,
                            Name = "Chanh Muối"
                        },
                        new
                        {
                            Id = "CAT20",
                            Description = "Thức uống signature của PolyCafe",
                            IsDeleted = false,
                            Name = "Đặc Biệt"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Drink", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = "D001",
                            CategoryId = "CAT01",
                            Description = "Cà phê phin truyền thống pha với sữa đặc và đá",
                            ImageUrl = "caphe_sua_da.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cà Phê Sữa Đá",
                            Price = 35000m
                        },
                        new
                        {
                            Id = "D002",
                            CategoryId = "CAT01",
                            Description = "Cà phê sữa tỉ lệ sữa nhiều hơn, thơm béo",
                            ImageUrl = "bac_xiu.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Bạc Xỉu",
                            Price = 35000m
                        },
                        new
                        {
                            Id = "D003",
                            CategoryId = "CAT02",
                            Description = "Trà sữa Đài Loan với trân châu đen dẻo dai",
                            ImageUrl = "trasua_tranchau.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Sữa Trân Châu Đen",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "D004",
                            CategoryId = "CAT02",
                            Description = "Trà sữa kết hợp matcha Nhật Bản thơm ngon",
                            ImageUrl = "trasua_matcha.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Sữa Matcha",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "D005",
                            CategoryId = "CAT03",
                            Description = "Sinh tố bơ sáp nguyên chất, béo thơm",
                            ImageUrl = "sinhto_bo.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sinh Tố Bơ",
                            Price = 55000m
                        },
                        new
                        {
                            Id = "D006",
                            CategoryId = "CAT03",
                            Description = "Xoài cát Hòa Lộc ngọt thơm xay mịn",
                            ImageUrl = "sinhto_xoai.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sinh Tố Xoài",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "D007",
                            CategoryId = "CAT04",
                            Description = "Cam vàng tươi nguyên chất, giàu vitamin C",
                            ImageUrl = "nuocep_cam.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Nước Ép Cam",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "D008",
                            CategoryId = "CAT04",
                            Description = "Dưa hấu đỏ tươi ngọt mát",
                            ImageUrl = "nuocep_duahau.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Nước Ép Dưa Hấu",
                            Price = 40000m
                        },
                        new
                        {
                            Id = "D009",
                            CategoryId = "CAT05",
                            Description = "Trà hoa đào kết hợp cam và sả tươi",
                            ImageUrl = "tradao_camsa.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Đào Cam Sả",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "D010",
                            CategoryId = "CAT05",
                            Description = "Trà xanh kết hợp vải và nhãn tươi mát",
                            ImageUrl = "travai_nhan.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Vải Nhãn",
                            Price = 48000m
                        },
                        new
                        {
                            Id = "D011",
                            CategoryId = "CAT06",
                            Description = "Bột matcha Nhật pha với sữa tươi và đá",
                            ImageUrl = "matcha_latte.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Matcha Latte Đá",
                            Price = 55000m
                        },
                        new
                        {
                            Id = "D012",
                            CategoryId = "CAT06",
                            Description = "Matcha xay đá mịn, thêm kem tươi phủ trên",
                            ImageUrl = "matcha_daxay.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Matcha Đá Xay",
                            Price = 60000m
                        },
                        new
                        {
                            Id = "D013",
                            CategoryId = "CAT07",
                            Description = "Chocolate Bỉ đun nóng, thêm marshmallow",
                            ImageUrl = "chocolate_nong.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Nóng",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "D014",
                            CategoryId = "CAT07",
                            Description = "Chocolate đá lạnh mát, béo ngậy",
                            ImageUrl = "chocolate_da.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Đá",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "D015",
                            CategoryId = "CAT08",
                            Description = "Cà phê xay đá caramel, phủ whipping cream",
                            ImageUrl = "frappuccino.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Frappuccino Caramel",
                            Price = 65000m
                        },
                        new
                        {
                            Id = "D016",
                            CategoryId = "CAT09",
                            Description = "Soda xi rô việt quất màu tím quyến rũ",
                            ImageUrl = "soda_vietquat.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Soda Việt Quất",
                            Price = 40000m
                        },
                        new
                        {
                            Id = "D017",
                            CategoryId = "CAT10",
                            Description = "Espresso pha với sữa hấp và xi rô vani",
                            ImageUrl = "latte_vani.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Latte Vani",
                            Price = 55000m
                        },
                        new
                        {
                            Id = "D018",
                            CategoryId = "CAT13",
                            Description = "Cold brew ủ lạnh 20 giờ, thêm nước cam tươi",
                            ImageUrl = "coldbrew_cam.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cold Brew Cam",
                            Price = 60000m
                        },
                        new
                        {
                            Id = "D019",
                            CategoryId = "CAT19",
                            Description = "Chanh leo tươi, muối hồng, đá bào mát lạnh",
                            ImageUrl = "chanhleo_muoi.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chanh Leo Muối",
                            Price = 38000m
                        },
                        new
                        {
                            Id = "D020",
                            CategoryId = "CAT20",
                            Description = "Thức uống bí mật của PolyCafe - vị đặc trưng không nơi nào có",
                            ImageUrl = "poly_signature.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "PolyCafe Signature",
                            Price = 75000m
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.DrinkHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DrinkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.ToTable("DrinkHistories");

                    b.HasData(
                        new
                        {
                            Id = "DH001",
                            CategoryId = "CAT01",
                            ChangedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cà phê phin truyền thống",
                            DrinkId = "D001",
                            ImageUrl = "caphe_sua_da.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cà Phê Sữa Đá",
                            Price = 30000m
                        },
                        new
                        {
                            Id = "DH002",
                            CategoryId = "CAT01",
                            ChangedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cà phê sữa tỉ lệ sữa nhiều hơn",
                            DrinkId = "D002",
                            ImageUrl = "bac_xiu.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Bạc Xỉu",
                            Price = 30000m
                        },
                        new
                        {
                            Id = "DH003",
                            CategoryId = "CAT02",
                            ChangedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà sữa Đài Loan",
                            DrinkId = "D003",
                            ImageUrl = "trasua_tranchau.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Sữa Trân Châu Đen",
                            Price = 40000m
                        },
                        new
                        {
                            Id = "DH004",
                            CategoryId = "CAT02",
                            ChangedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà sữa matcha Nhật",
                            DrinkId = "D004",
                            ImageUrl = "trasua_matcha.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Sữa Matcha",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "DH005",
                            CategoryId = "CAT03",
                            ChangedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sinh tố bơ sáp",
                            DrinkId = "D005",
                            ImageUrl = "sinhto_bo.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sinh Tố Bơ",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "DH006",
                            CategoryId = "CAT03",
                            ChangedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xoài cát Hòa Lộc",
                            DrinkId = "D006",
                            ImageUrl = "sinhto_xoai.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Sinh Tố Xoài",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "DH007",
                            CategoryId = "CAT04",
                            ChangedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cam vàng nguyên chất",
                            DrinkId = "D007",
                            ImageUrl = "nuocep_cam.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Nước Ép Cam",
                            Price = 40000m
                        },
                        new
                        {
                            Id = "DH008",
                            CategoryId = "CAT04",
                            ChangedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dưa hấu đỏ tươi",
                            DrinkId = "D008",
                            ImageUrl = "nuocep_duahau.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Nước Ép Dưa Hấu",
                            Price = 35000m
                        },
                        new
                        {
                            Id = "DH009",
                            CategoryId = "CAT05",
                            ChangedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà hoa đào",
                            DrinkId = "D009",
                            ImageUrl = "tradao_camsa.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Đào Cam Sả",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "DH010",
                            CategoryId = "CAT05",
                            ChangedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trà xanh vải nhãn",
                            DrinkId = "D010",
                            ImageUrl = "travai_nhan.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Trà Vải Nhãn",
                            Price = 43000m
                        },
                        new
                        {
                            Id = "DH011",
                            CategoryId = "CAT06",
                            ChangedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matcha sữa đá",
                            DrinkId = "D011",
                            ImageUrl = "matcha_latte.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Matcha Latte Đá",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "DH012",
                            CategoryId = "CAT06",
                            ChangedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matcha xay đá",
                            DrinkId = "D012",
                            ImageUrl = "matcha_daxay.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Matcha Đá Xay",
                            Price = 55000m
                        },
                        new
                        {
                            Id = "DH013",
                            CategoryId = "CAT07",
                            ChangedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chocolate Bỉ nóng",
                            DrinkId = "D013",
                            ImageUrl = "chocolate_nong.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Nóng",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "DH014",
                            CategoryId = "CAT07",
                            ChangedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chocolate đá lạnh",
                            DrinkId = "D014",
                            ImageUrl = "chocolate_da.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Đá",
                            Price = 45000m
                        },
                        new
                        {
                            Id = "DH015",
                            CategoryId = "CAT08",
                            ChangedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cà phê xay caramel",
                            DrinkId = "D015",
                            ImageUrl = "frappuccino.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Frappuccino Caramel",
                            Price = 60000m
                        },
                        new
                        {
                            Id = "DH016",
                            CategoryId = "CAT09",
                            ChangedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Soda việt quất",
                            DrinkId = "D016",
                            ImageUrl = "soda_vietquat.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Soda Việt Quất",
                            Price = 35000m
                        },
                        new
                        {
                            Id = "DH017",
                            CategoryId = "CAT10",
                            ChangedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latte xi rô vani",
                            DrinkId = "D017",
                            ImageUrl = "latte_vani.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Latte Vani",
                            Price = 50000m
                        },
                        new
                        {
                            Id = "DH018",
                            CategoryId = "CAT13",
                            ChangedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cold brew cam tươi",
                            DrinkId = "D018",
                            ImageUrl = "coldbrew_cam.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cold Brew Cam",
                            Price = 55000m
                        },
                        new
                        {
                            Id = "DH019",
                            CategoryId = "CAT19",
                            ChangedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chanh leo muối đá",
                            DrinkId = "D019",
                            ImageUrl = "chanhleo_muoi.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chanh Leo Muối",
                            Price = 33000m
                        },
                        new
                        {
                            Id = "DH020",
                            CategoryId = "CAT20",
                            ChangedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thức uống bí mật cũ",
                            DrinkId = "D020",
                            ImageUrl = "poly_signature.jpg",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "PolyCafe Signature",
                            Price = 70000m
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.DrinkVariant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrinkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.ToTable("DrinkVariants");

                    b.HasData(
                        new
                        {
                            Id = "DV001",
                            DrinkId = "D001",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Size S"
                        },
                        new
                        {
                            Id = "DV002",
                            DrinkId = "D001",
                            ExtraPrice = 5000m,
                            IsActive = true,
                            VariantName = "Size M"
                        },
                        new
                        {
                            Id = "DV003",
                            DrinkId = "D001",
                            ExtraPrice = 10000m,
                            IsActive = true,
                            VariantName = "Size L"
                        },
                        new
                        {
                            Id = "DV004",
                            DrinkId = "D003",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Ít đường"
                        },
                        new
                        {
                            Id = "DV005",
                            DrinkId = "D003",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Không đường"
                        },
                        new
                        {
                            Id = "DV006",
                            DrinkId = "D003",
                            ExtraPrice = 8000m,
                            IsActive = true,
                            VariantName = "Thêm trân châu"
                        },
                        new
                        {
                            Id = "DV007",
                            DrinkId = "D005",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Không đường"
                        },
                        new
                        {
                            Id = "DV008",
                            DrinkId = "D005",
                            ExtraPrice = 5000m,
                            IsActive = true,
                            VariantName = "Thêm sữa đặc"
                        },
                        new
                        {
                            Id = "DV009",
                            DrinkId = "D011",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Matcha vị nhẹ"
                        },
                        new
                        {
                            Id = "DV010",
                            DrinkId = "D011",
                            ExtraPrice = 5000m,
                            IsActive = true,
                            VariantName = "Matcha vị đậm"
                        },
                        new
                        {
                            Id = "DV011",
                            DrinkId = "D015",
                            ExtraPrice = 5000m,
                            IsActive = true,
                            VariantName = "Thêm caramel drizzle"
                        },
                        new
                        {
                            Id = "DV012",
                            DrinkId = "D015",
                            ExtraPrice = 10000m,
                            IsActive = true,
                            VariantName = "Thêm extra espresso"
                        },
                        new
                        {
                            Id = "DV013",
                            DrinkId = "D017",
                            ExtraPrice = 10000m,
                            IsActive = true,
                            VariantName = "Sữa hạnh nhân"
                        },
                        new
                        {
                            Id = "DV014",
                            DrinkId = "D017",
                            ExtraPrice = 10000m,
                            IsActive = true,
                            VariantName = "Sữa yến mạch"
                        },
                        new
                        {
                            Id = "DV015",
                            DrinkId = "D020",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Size S"
                        },
                        new
                        {
                            Id = "DV016",
                            DrinkId = "D020",
                            ExtraPrice = 15000m,
                            IsActive = true,
                            VariantName = "Size L"
                        },
                        new
                        {
                            Id = "DV017",
                            DrinkId = "D009",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Ít đá"
                        },
                        new
                        {
                            Id = "DV018",
                            DrinkId = "D009",
                            ExtraPrice = 0m,
                            IsActive = true,
                            VariantName = "Không đá"
                        },
                        new
                        {
                            Id = "DV019",
                            DrinkId = "D012",
                            ExtraPrice = 8000m,
                            IsActive = true,
                            VariantName = "Thêm kem tươi"
                        },
                        new
                        {
                            Id = "DV020",
                            DrinkId = "D013",
                            ExtraPrice = 5000m,
                            IsActive = true,
                            VariantName = "Thêm marshmallow"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "ORD001",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 80000m,
                            UserId = "U002"
                        },
                        new
                        {
                            Id = "ORD002",
                            DiscountAmount = 9000m,
                            OrderDate = new DateTime(2025, 1, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 90000m,
                            UserId = "U003",
                            VoucherId = "V001"
                        },
                        new
                        {
                            Id = "ORD003",
                            DiscountAmount = 20000m,
                            OrderDate = new DateTime(2025, 1, 12, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 105000m,
                            UserId = "U004",
                            VoucherId = "V002"
                        },
                        new
                        {
                            Id = "ORD004",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 70000m,
                            UserId = "U005"
                        },
                        new
                        {
                            Id = "ORD005",
                            DiscountAmount = 15000m,
                            OrderDate = new DateTime(2025, 1, 14, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 120000m,
                            UserId = "U002",
                            VoucherId = "V004"
                        },
                        new
                        {
                            Id = "ORD006",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPrice = 55000m,
                            UserId = "U003"
                        },
                        new
                        {
                            Id = "ORD007",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 160000m,
                            UserId = "U004"
                        },
                        new
                        {
                            Id = "ORD008",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            TotalPrice = 75000m,
                            UserId = "U005"
                        },
                        new
                        {
                            Id = "ORD009",
                            DiscountAmount = 40000m,
                            OrderDate = new DateTime(2025, 1, 18, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 200000m,
                            UserId = "U002",
                            VoucherId = "V005"
                        },
                        new
                        {
                            Id = "ORD010",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 19, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 85000m,
                            UserId = "U003"
                        },
                        new
                        {
                            Id = "ORD011",
                            DiscountAmount = 11000m,
                            OrderDate = new DateTime(2025, 1, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 110000m,
                            UserId = "U004",
                            VoucherId = "V001"
                        },
                        new
                        {
                            Id = "ORD012",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 21, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalPrice = 95000m,
                            UserId = "U005"
                        },
                        new
                        {
                            Id = "ORD013",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 22, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 45000m,
                            UserId = "U002"
                        },
                        new
                        {
                            Id = "ORD014",
                            DiscountAmount = 20000m,
                            OrderDate = new DateTime(2025, 1, 23, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 135000m,
                            UserId = "U003",
                            VoucherId = "V002"
                        },
                        new
                        {
                            Id = "ORD015",
                            DiscountAmount = 6000m,
                            OrderDate = new DateTime(2025, 1, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 60000m,
                            UserId = "U004",
                            VoucherId = "V009"
                        },
                        new
                        {
                            Id = "ORD016",
                            DiscountAmount = 36000m,
                            OrderDate = new DateTime(2025, 1, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 180000m,
                            UserId = "U005",
                            VoucherId = "V005"
                        },
                        new
                        {
                            Id = "ORD017",
                            DiscountAmount = 0m,
                            OrderDate = new DateTime(2025, 1, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 50000m,
                            UserId = "U002"
                        },
                        new
                        {
                            Id = "ORD018",
                            DiscountAmount = 15000m,
                            OrderDate = new DateTime(2025, 1, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 145000m,
                            UserId = "U003",
                            VoucherId = "V004"
                        },
                        new
                        {
                            Id = "ORD019",
                            DiscountAmount = 11250m,
                            OrderDate = new DateTime(2025, 1, 28, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 75000m,
                            UserId = "U004",
                            VoucherId = "V019"
                        },
                        new
                        {
                            Id = "ORD020",
                            DiscountAmount = 56250m,
                            OrderDate = new DateTime(2025, 1, 29, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            TotalPrice = 225000m,
                            UserId = "U005",
                            VoucherId = "V020"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.OrderDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrinkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VariantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VariantId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = "OD001",
                            DrinkId = "D001",
                            OrderId = "ORD001",
                            Quantity = 2,
                            UnitPrice = 40000m,
                            VariantId = "DV002"
                        },
                        new
                        {
                            Id = "OD002",
                            DrinkId = "D003",
                            OrderId = "ORD002",
                            Quantity = 2,
                            UnitPrice = 53000m,
                            VariantId = "DV006"
                        },
                        new
                        {
                            Id = "OD003",
                            DrinkId = "D005",
                            OrderId = "ORD003",
                            Quantity = 1,
                            UnitPrice = 60000m,
                            VariantId = "DV008"
                        },
                        new
                        {
                            Id = "OD004",
                            DrinkId = "D009",
                            OrderId = "ORD003",
                            Quantity = 1,
                            UnitPrice = 50000m
                        },
                        new
                        {
                            Id = "OD005",
                            DrinkId = "D007",
                            OrderId = "ORD004",
                            Quantity = 1,
                            UnitPrice = 45000m
                        },
                        new
                        {
                            Id = "OD006",
                            DrinkId = "D019",
                            OrderId = "ORD004",
                            Quantity = 1,
                            UnitPrice = 38000m
                        },
                        new
                        {
                            Id = "OD007",
                            DrinkId = "D015",
                            OrderId = "ORD005",
                            Quantity = 1,
                            UnitPrice = 70000m,
                            VariantId = "DV011"
                        },
                        new
                        {
                            Id = "OD008",
                            DrinkId = "D011",
                            OrderId = "ORD005",
                            Quantity = 1,
                            UnitPrice = 60000m,
                            VariantId = "DV010"
                        },
                        new
                        {
                            Id = "OD009",
                            DrinkId = "D002",
                            OrderId = "ORD006",
                            Quantity = 1,
                            UnitPrice = 35000m
                        },
                        new
                        {
                            Id = "OD010",
                            DrinkId = "D020",
                            OrderId = "ORD007",
                            Quantity = 2,
                            UnitPrice = 90000m,
                            VariantId = "DV016"
                        },
                        new
                        {
                            Id = "OD011",
                            DrinkId = "D013",
                            OrderId = "ORD008",
                            Quantity = 1,
                            UnitPrice = 55000m,
                            VariantId = "DV020"
                        },
                        new
                        {
                            Id = "OD012",
                            DrinkId = "D015",
                            OrderId = "ORD009",
                            Quantity = 2,
                            UnitPrice = 75000m,
                            VariantId = "DV012"
                        },
                        new
                        {
                            Id = "OD013",
                            DrinkId = "D004",
                            OrderId = "ORD010",
                            Quantity = 1,
                            UnitPrice = 50000m
                        },
                        new
                        {
                            Id = "OD014",
                            DrinkId = "D016",
                            OrderId = "ORD010",
                            Quantity = 1,
                            UnitPrice = 40000m
                        },
                        new
                        {
                            Id = "OD015",
                            DrinkId = "D018",
                            OrderId = "ORD011",
                            Quantity = 1,
                            UnitPrice = 60000m
                        },
                        new
                        {
                            Id = "OD016",
                            DrinkId = "D006",
                            OrderId = "ORD012",
                            Quantity = 2,
                            UnitPrice = 50000m
                        },
                        new
                        {
                            Id = "OD017",
                            DrinkId = "D001",
                            OrderId = "ORD013",
                            Quantity = 1,
                            UnitPrice = 35000m,
                            VariantId = "DV001"
                        },
                        new
                        {
                            Id = "OD018",
                            DrinkId = "D012",
                            OrderId = "ORD014",
                            Quantity = 2,
                            UnitPrice = 68000m,
                            VariantId = "DV019"
                        },
                        new
                        {
                            Id = "OD019",
                            DrinkId = "D017",
                            OrderId = "ORD015",
                            Quantity = 1,
                            UnitPrice = 65000m,
                            VariantId = "DV013"
                        },
                        new
                        {
                            Id = "OD020",
                            DrinkId = "D020",
                            OrderId = "ORD016",
                            Quantity = 2,
                            UnitPrice = 75000m,
                            VariantId = "DV015"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Role")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            Address = "123 Lê Lợi, Q1, HCM",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@polycafe.vn",
                            FullName = "Admin PolyCafe",
                            IsActive = true,
                            Password = "admin123",
                            Phone = "0900000001",
                            Role = true
                        },
                        new
                        {
                            Id = "U002",
                            Address = "45 Nguyễn Huệ, Q1, HCM",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "an@gmail.com",
                            FullName = "Nguyễn Văn An",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0901234567",
                            Role = false
                        },
                        new
                        {
                            Id = "U003",
                            Address = "78 Trần Hưng Đạo, Q5, HCM",
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bich@gmail.com",
                            FullName = "Trần Thị Bích",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0912345678",
                            Role = false
                        },
                        new
                        {
                            Id = "U004",
                            Address = "12 Võ Văn Tần, Q3, HCM",
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cuong@gmail.com",
                            FullName = "Lê Văn Cường",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0923456789",
                            Role = false
                        },
                        new
                        {
                            Id = "U005",
                            Address = "99 CMT8, Q10, HCM",
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dung@gmail.com",
                            FullName = "Phạm Thị Dung",
                            IsActive = true,
                            Password = "123456",
                            Phone = "0934567890",
                            Role = false
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Voucher", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            Id = "V001",
                            Code = "WELCOME10",
                            DiscountType = "percent",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Chào mừng khách mới",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 5
                        },
                        new
                        {
                            Id = "V002",
                            Code = "GIAM20K",
                            DiscountType = "fixed",
                            DiscountValue = 20000m,
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Giảm 20.000đ đơn từ 100k",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 50,
                            UsedCount = 10
                        },
                        new
                        {
                            Id = "V003",
                            Code = "POLY15",
                            DiscountType = "percent",
                            DiscountValue = 15m,
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "PolyCafe 15%",
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 200,
                            UsedCount = 80
                        },
                        new
                        {
                            Id = "V004",
                            Code = "FREESHIP",
                            DiscountType = "fixed",
                            DiscountValue = 15000m,
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Miễn phí giao hàng",
                            StartDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 300,
                            UsedCount = 45
                        },
                        new
                        {
                            Id = "V005",
                            Code = "TETHOLIDAY",
                            DiscountType = "percent",
                            DiscountValue = 20m,
                            EndDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Khuyến mãi Tết 2025",
                            StartDate = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 500,
                            UsedCount = 320
                        },
                        new
                        {
                            Id = "V006",
                            Code = "BIRTHDAY30",
                            DiscountType = "percent",
                            DiscountValue = 30m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sinh nhật giảm 30%",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 1,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = "V007",
                            Code = "COMBO50K",
                            DiscountType = "fixed",
                            DiscountValue = 50000m,
                            EndDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Giảm 50k đơn combo",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 20
                        },
                        new
                        {
                            Id = "V008",
                            Code = "SUMMER25",
                            DiscountType = "percent",
                            DiscountValue = 25m,
                            EndDate = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Summer Sale 25%",
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 400,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = "V009",
                            Code = "LOYAL5",
                            DiscountType = "percent",
                            DiscountValue = 5m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Khách thân thiết 5%",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 9999,
                            UsedCount = 150
                        },
                        new
                        {
                            Id = "V010",
                            Code = "FIRSTAPP",
                            DiscountType = "fixed",
                            DiscountValue = 30000m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Lần đầu đặt app",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 1,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = "V011",
                            Code = "FLASH20",
                            DiscountType = "percent",
                            DiscountValue = 20m,
                            EndDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "Flash Sale 20%",
                            StartDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 50,
                            UsedCount = 50
                        },
                        new
                        {
                            Id = "V012",
                            Code = "WEEKDAY10",
                            DiscountType = "percent",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ngày thường giảm 10%",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 9999,
                            UsedCount = 200
                        },
                        new
                        {
                            Id = "V013",
                            Code = "MORNING15K",
                            DiscountType = "fixed",
                            DiscountValue = 15000m,
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Buổi sáng giảm 15k",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 200,
                            UsedCount = 60
                        },
                        new
                        {
                            Id = "V014",
                            Code = "GROUP100K",
                            DiscountType = "fixed",
                            DiscountValue = 100000m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Nhóm đặt giảm 100k",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 30,
                            UsedCount = 5
                        },
                        new
                        {
                            Id = "V015",
                            Code = "ECO10",
                            DiscountType = "percent",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Giảm 10% mang ly riêng",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 9999,
                            UsedCount = 90
                        },
                        new
                        {
                            Id = "V016",
                            Code = "REVIEW20K",
                            DiscountType = "fixed",
                            DiscountValue = 20000m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Đánh giá 5 sao giảm 20k",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 500,
                            UsedCount = 30
                        },
                        new
                        {
                            Id = "V017",
                            Code = "NEWMENU",
                            DiscountType = "percent",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Thử menu mới giảm 10%",
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = "V018",
                            Code = "RAINY10K",
                            DiscountType = "fixed",
                            DiscountValue = 10000m,
                            EndDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ngày mưa giảm 10k",
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 9999,
                            UsedCount = 0
                        },
                        new
                        {
                            Id = "V019",
                            Code = "MIDNIGHT",
                            DiscountType = "percent",
                            DiscountValue = 15m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Đêm khuya giảm 15%",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 100,
                            UsedCount = 10
                        },
                        new
                        {
                            Id = "V020",
                            Code = "POLY2025",
                            DiscountType = "percent",
                            DiscountValue = 25m,
                            EndDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            Name = "PolyCafe kỷ niệm 2025",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 1000,
                            UsedCount = 750
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.VoucherDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ConditionValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VoucherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherDetails");

                    b.HasData(
                        new
                        {
                            Id = "VD001",
                            ConditionType = "MinOrder",
                            ConditionValue = 50000m,
                            Description = "Đơn tối thiểu 50.000đ",
                            VoucherId = "V001"
                        },
                        new
                        {
                            Id = "VD002",
                            ConditionType = "MinOrder",
                            ConditionValue = 100000m,
                            Description = "Đơn tối thiểu 100.000đ",
                            VoucherId = "V002"
                        },
                        new
                        {
                            Id = "VD003",
                            ConditionType = "MinOrder",
                            ConditionValue = 80000m,
                            Description = "Đơn tối thiểu 80.000đ",
                            VoucherId = "V003"
                        },
                        new
                        {
                            Id = "VD004",
                            ConditionType = "MinOrder",
                            ConditionValue = 60000m,
                            Description = "Đơn tối thiểu 60.000đ",
                            VoucherId = "V004"
                        },
                        new
                        {
                            Id = "VD005",
                            ConditionType = "MinOrder",
                            ConditionValue = 100000m,
                            Description = "Đơn tối thiểu 100.000đ",
                            VoucherId = "V005"
                        },
                        new
                        {
                            Id = "VD006",
                            ConditionType = "BirthdayMonth",
                            ConditionValue = 1m,
                            Description = "Áp dụng trong tháng sinh nhật",
                            VoucherId = "V006"
                        },
                        new
                        {
                            Id = "VD007",
                            ConditionType = "MinOrder",
                            ConditionValue = 150000m,
                            Description = "Đơn combo tối thiểu 150.000đ",
                            VoucherId = "V007"
                        },
                        new
                        {
                            Id = "VD008",
                            ConditionType = "MinOrder",
                            ConditionValue = 70000m,
                            Description = "Đơn tối thiểu 70.000đ",
                            VoucherId = "V008"
                        },
                        new
                        {
                            Id = "VD009",
                            ConditionType = "MinOrder",
                            ConditionValue = 0m,
                            Description = "Không giới hạn đơn hàng",
                            VoucherId = "V009"
                        },
                        new
                        {
                            Id = "VD010",
                            ConditionType = "FirstOrder",
                            ConditionValue = 1m,
                            Description = "Chỉ áp dụng đơn hàng đầu tiên",
                            VoucherId = "V010"
                        },
                        new
                        {
                            Id = "VD011",
                            ConditionType = "MinOrder",
                            ConditionValue = 50000m,
                            Description = "Flash sale đơn từ 50k",
                            VoucherId = "V011"
                        },
                        new
                        {
                            Id = "VD012",
                            ConditionType = "DayOfWeek",
                            ConditionValue = 5m,
                            Description = "Thứ 2 đến thứ 6",
                            VoucherId = "V012"
                        },
                        new
                        {
                            Id = "VD013",
                            ConditionType = "TimeRange",
                            ConditionValue = 9m,
                            Description = "Áp dụng 6h-9h sáng",
                            VoucherId = "V013"
                        },
                        new
                        {
                            Id = "VD014",
                            ConditionType = "MinOrder",
                            ConditionValue = 300000m,
                            Description = "Đơn nhóm tối thiểu 300.000đ",
                            VoucherId = "V014"
                        },
                        new
                        {
                            Id = "VD015",
                            ConditionType = "EcoCup",
                            ConditionValue = 1m,
                            Description = "Mang ly cá nhân khi đến quán",
                            VoucherId = "V015"
                        },
                        new
                        {
                            Id = "VD016",
                            ConditionType = "ReviewRequired",
                            ConditionValue = 5m,
                            Description = "Đánh giá 5 sao lần đặt trước",
                            VoucherId = "V016"
                        },
                        new
                        {
                            Id = "VD017",
                            ConditionType = "NewItem",
                            ConditionValue = 1m,
                            Description = "Áp dụng khi đặt món trong menu mới",
                            VoucherId = "V017"
                        },
                        new
                        {
                            Id = "VD018",
                            ConditionType = "MinOrder",
                            ConditionValue = 40000m,
                            Description = "Đơn tối thiểu 40.000đ",
                            VoucherId = "V018"
                        },
                        new
                        {
                            Id = "VD019",
                            ConditionType = "TimeRange",
                            ConditionValue = 22m,
                            Description = "Áp dụng từ 22h - 24h",
                            VoucherId = "V019"
                        },
                        new
                        {
                            Id = "VD020",
                            ConditionType = "MinOrder",
                            ConditionValue = 50000m,
                            Description = "Kỷ niệm thành lập quán",
                            VoucherId = "V020"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.VoucherScope", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ApplyType")
                        .HasColumnType("int");

                    b.Property<string>("DrinkId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VoucherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherScopes");

                    b.HasData(
                        new
                        {
                            Id = "VS001",
                            ApplyType = 0,
                            VoucherId = "V001"
                        },
                        new
                        {
                            Id = "VS002",
                            ApplyType = 0,
                            VoucherId = "V002"
                        },
                        new
                        {
                            Id = "VS003",
                            ApplyType = 0,
                            VoucherId = "V003"
                        },
                        new
                        {
                            Id = "VS004",
                            ApplyType = 0,
                            VoucherId = "V004"
                        },
                        new
                        {
                            Id = "VS005",
                            ApplyType = 0,
                            VoucherId = "V005"
                        },
                        new
                        {
                            Id = "VS006",
                            ApplyType = 0,
                            VoucherId = "V006"
                        },
                        new
                        {
                            Id = "VS007",
                            ApplyType = 0,
                            VoucherId = "V007"
                        },
                        new
                        {
                            Id = "VS008",
                            ApplyType = 0,
                            VoucherId = "V008"
                        },
                        new
                        {
                            Id = "VS009",
                            ApplyType = 0,
                            VoucherId = "V009"
                        },
                        new
                        {
                            Id = "VS010",
                            ApplyType = 0,
                            VoucherId = "V010"
                        },
                        new
                        {
                            Id = "VS011",
                            ApplyType = 1,
                            DrinkId = "D020",
                            VoucherId = "V011"
                        },
                        new
                        {
                            Id = "VS012",
                            ApplyType = 1,
                            DrinkId = "D001",
                            VoucherId = "V012"
                        },
                        new
                        {
                            Id = "VS013",
                            ApplyType = 1,
                            DrinkId = "D002",
                            VoucherId = "V013"
                        },
                        new
                        {
                            Id = "VS014",
                            ApplyType = 0,
                            VoucherId = "V014"
                        },
                        new
                        {
                            Id = "VS015",
                            ApplyType = 0,
                            VoucherId = "V015"
                        },
                        new
                        {
                            Id = "VS016",
                            ApplyType = 0,
                            VoucherId = "V016"
                        },
                        new
                        {
                            Id = "VS017",
                            ApplyType = 1,
                            DrinkId = "D019",
                            VoucherId = "V017"
                        },
                        new
                        {
                            Id = "VS018",
                            ApplyType = 0,
                            VoucherId = "V018"
                        },
                        new
                        {
                            Id = "VS019",
                            ApplyType = 0,
                            VoucherId = "V019"
                        },
                        new
                        {
                            Id = "VS020",
                            ApplyType = 0,
                            VoucherId = "V020"
                        });
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Drink", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Category", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.DrinkHistory", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Drink", "Drink")
                        .WithMany("DrinkHistories")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.DrinkVariant", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Drink", "Drink")
                        .WithMany("DrinkVariants")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Order", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_QuanLy_PolyCafe.Models.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("VoucherId");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.OrderDetail", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Drink", "Drink")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_QuanLy_PolyCafe.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_QuanLy_PolyCafe.Models.DrinkVariant", "Variant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VariantId");

                    b.Navigation("Drink");

                    b.Navigation("Order");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.VoucherDetail", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Voucher", "Voucher")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.VoucherScope", b =>
                {
                    b.HasOne("Web_QuanLy_PolyCafe.Models.Drink", "Drink")
                        .WithMany("VoucherScopes")
                        .HasForeignKey("DrinkId");

                    b.HasOne("Web_QuanLy_PolyCafe.Models.Voucher", "Voucher")
                        .WithMany("VoucherScopes")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Category", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Drink", b =>
                {
                    b.Navigation("DrinkHistories");

                    b.Navigation("DrinkVariants");

                    b.Navigation("OrderDetails");

                    b.Navigation("VoucherScopes");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.DrinkVariant", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Web_QuanLy_PolyCafe.Models.Voucher", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("VoucherDetails");

                    b.Navigation("VoucherScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
